### ISSUE TITLE
Marauder Mini

### ISSUE THREAD

**Issue by Drotnip** [bmorcelli/M5Stick-Launcher#97]
To be able to log into WUI I need to log into my internet. Typing in the password it skips places and won't allow me to log in. It worked in the past but doesn't now. It won't let me log in to be able to change it on wui because of the typing of wrong password via tactical button. ![VideoCapture_20250102-111006.jpg](https://github.com/user-attachments/assets/3668ba9c-4167-438a-9868-2b6a442db2c5)

**Comment by bmorcelli** [comment]
Can you please test if it is happening in the BetaRelease?

I believe I fixed it on Beta

**Comment by Drotnip** [comment]
I will be home shortly. I will test it on Beta.

**Comment by Drotnip** [comment]
Its still not working. Its even overlaps other numbers and skips spaces

**Comment by Drotnip** [comment]
When I go to delete the pswd it leaves digits in place.

**Comment by bmorcelli** [comment]
Can you please test the Beta release, please?

**Comment by Drotnip** [comment]
Will do right now.

**Comment by Drotnip** [comment]
Pirata, it works now. 100%. Thank you, Sir.
